<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup>
    <Compile Include="../../WildGlow/MoteMotion.cs" Link="MoteMotion.cs" />
    <Compile Include="../../WildGlow/MoteArt.cs" Link="MoteArt.cs" />
  </ItemGroup>
</Project>
