<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GamePath Condition="'$(GamePath)' == ''">/home/deck/.steam/steam/steamapps/common/Valheim</GamePath>
  </PropertyGroup>
  <ItemGroup><Reference Include="Mono.Cecil"><HintPath>$(GamePath)/BepInEx/core/Mono.Cecil.dll</HintPath></Reference></ItemGroup>
</Project>
