<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AutomaticallyUseReferenceAssemblyPackages>false</AutomaticallyUseReferenceAssemblyPackages>
    <LangVersion>latest</LangVersion>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <AssemblyName>WildGlow</AssemblyName>
    <Version>0.4.12</Version>
    <GamePath Condition="'$(GamePath)' == ''">/home/deck/.steam/steam/steamapps/common/Valheim</GamePath>
    <ManagedPath>$(GamePath)/valheim_Data/Managed</ManagedPath>
    <FrameworkPathOverride>$(ManagedPath)</FrameworkPathOverride>
    <BepInExPath Condition="'$(BepInExPath)' == ''">$(GamePath)/BepInEx/core</BepInExPath>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="netstandard"><HintPath>$(ManagedPath)/netstandard.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.Net.Http"><HintPath>$(ManagedPath)/System.Net.Http.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="System.IO.Compression"><HintPath>$(ManagedPath)/System.IO.Compression.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_valheim"><HintPath>$(ManagedPath)/assembly_valheim.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="assembly_utils"><HintPath>$(ManagedPath)/assembly_utils.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="BepInEx"><HintPath>$(BepInExPath)/BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(BepInExPath)/0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(ManagedPath)/UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(ManagedPath)/UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ParticleSystemModule"><HintPath>$(ManagedPath)/UnityEngine.ParticleSystemModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>$(ManagedPath)/UnityEngine.PhysicsModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.ImageConversionModule"><HintPath>$(ManagedPath)/UnityEngine.ImageConversionModule.dll</HintPath><Private>false</Private></Reference>
    <EmbeddedResource Include="../effects.tsv" LogicalName="WildGlow.effects.tsv" />
  </ItemGroup>
</Project>
