using System;
using System.Collections.Generic;
using System.Numerics;
using UnityEngine;
using WildGlow;
using Vector3=UnityEngine.Vector3;
int checks=0;
void Check(bool pass,string why){checks++;if(!pass)throw new Exception(why);}
var bounds=new Bounds{center=new Vector3(.07420105f,2.10389733f,.02755487f),extents=new Vector3(.41979003f,.71005362f,.41924551f)};
var fruit=new GameObject();var transform=new Transform{gameObject=fruit};
var mesh=new Mesh{name="apple",vertexCount=1792,bounds=bounds};
var renderer=new MeshRenderer{bounds=bounds};
fruit.filters.Add(new MeshFilter{sharedMesh=mesh,renderer=renderer,transform=transform});
var anchors=new List<SurfaceAnchor>();
Check(FruitSurface.IsTree("apple_tree") && FruitSurface.IsTree("apple_tree_1"),"Missing installed tree variant");
Check(!FruitSurface.IsTree("sapling_apple_tree") && !FruitSurface.IsTree("apple") && !FruitSurface.IsTree("Beech"),"Fruit handling leaked into saplings, items or ordinary trees");
Check(FruitSurface.Prepare(fruit,anchors,out var measured) && anchors.Count==9,"Combined unreadable fruit mesh must produce nine anchors without reading vertices");
foreach(var a in anchors)Check(a.Valid && a.Local.y>1.5f && a.Local.y<2.83f && a.Renderer==renderer,"Anchor is below fruit, invalid, or bound to another renderer");
var original=new List<SurfaceAnchor>(anchors);
transform.matrix=Matrix4x4.CreateScale(2,3,4)*Matrix4x4.CreateRotationY(.7f)*Matrix4x4.CreateTranslation(20,10,-30);
Check(FruitSurface.Prepare(fruit,anchors,out _) && anchors.Count==9,"Transformed tree lost fruit anchors");
for(int i=0;i<anchors.Count;i++)Check((anchors[i].World-transform.TransformPoint(original[i].Local)).sqrMagnitude<.000001f,"Tree rotation/scale moved the effects away from the apples");
fruit.activeInHierarchy=false;
Check(original.TrueForAll(a=>!a.Valid),"Harvested fruit retains valid anchors");
Check(!FruitSurface.Prepare(fruit,anchors,out _) && anchors.Count==0,"Harvest falls back to stale tree anchors");
fruit.activeInHierarchy=true;
Check(FruitSurface.Prepare(fruit,anchors,out _) && anchors.Count==9,"Regrown fruit does not restore anchors");
renderer.enabled=false;Check(!FruitSurface.Prepare(fruit,anchors,out _) && anchors.Count==0,"Disabled renderer retains glow anchors");renderer.enabled=true;
renderer.forceRenderingOff=true;Check(!FruitSurface.Prepare(fruit,anchors,out _),"Force-hidden fruit retains anchors");renderer.forceRenderingOff=false;
mesh.vertexCount++;Check(!FruitSurface.Prepare(fruit,anchors,out _) && anchors.Count==0,"Changed mesh accepted stale compatibility points");mesh.vertexCount--;
mesh.name="beech";Check(!FruitSurface.Prepare(fruit,anchors,out _),"Trunk accepted as fruit");mesh.name="apple";
mesh.bounds=new Bounds{center=new Vector3(0,0,0),extents=bounds.extents};Check(!FruitSurface.Prepare(fruit,anchors,out _),"Repositioned mesh accepted old anchors");
Check(!FruitSurface.Prepare(null,anchors,out _) && anchors.Count==0,"Missing harvest mesh falls back to the tree");
Console.WriteLine($"PASS: {checks} fruit attachment/lifecycle checks (transform test doubles; no GPU rendering).");
